all:
	d2 --layout=elk symbology_widget.d2 symbology_widget.png

# For this one, elk > dagre
# d2 --layout=dagre symbology_widget.d2 symbology_widget_dagre.png

# I've given up on graphviz/dot
# dot -Tpng symbology_widget.dot > symbology_widget.png
